### PR TITLE
Eliminated Aspect Mock usage from ActionMergeUtilTest

### PR DESCRIPTION
**Pull request by vlmed**
### Description
This PR will pass all tests after related PR will be merged

Eliminated Aspect Mock usage from ActionMergeUtilTest: `dev/tests/unit/Magento/FunctionalTestFramework/Test/Util/ActionMergeUtilTest.php`

### Related Pull Requests
https://github.com/magento/magento2-functional-testing-framework/pull/849

### Fixed Issues (if relevant)
1. magento/magento2#33304: [MFTF] Replace AspectMock with PHPUnit for ActionMergeUtilTest

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/verification tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)
 - [ ] Changes to Framework doesn't have backward incompatible changes for tests or have related Pull Request with fixes to tests

### CODE REVIEW

**Comment by sivaschenko** [comment]
@vlmed was this PR closed intentionally?

**Comment by vlmed** [comment]
@sivaschenko. Yes i have closed this PR. When I run only this test, it passes without errors, if I run with all the tests, it does not pass. The reason is in `AspectMock::double(DataObjectHandler::class, ['getInstance' => $mockDOHInstance]);` static method. Looks like if we fully remove AspectMock from project my changes in the test should work. I can reopen PR if this changes is correct

**Comment by sivaschenko** [comment]
Got it, thanks @vlmed . I will add your PR to the issue description and unassign you from the issue

**Comment by bohdan-harniuk** [comment]
Hello, @jilu1

I have a little bit helped for @vlmed with the aspect mock elimination here. Now all tests run fine.

The problem was that AspectMock mocked the getInstance method of the DataObjectHandler class. In this test, we set mock to the INSTANCE variable through the ReflectionProperty. But we got the wrong mock instance, mocked by the AspectMock (the INSTANCE variable checked in the getInstance method...getInstance method mocked by the AspectMock and that mocked object returned before our mock on the INSTANCE variable).

cc: @vlmed , @sivaschenko

**Review by bohdan-harniuk — APPROVED** [review]
It is fine for me. @vlmed, thank you for your contribution.

@jilu1, could you please take a look at this PR too?

**Review by andrewbess — APPROVED** [review]
Hello @vlmed 
Thank you for your contribution.
Hello @bohdan-harniuk 
Thank you for your helping @vlmed 
The changes look great for me.

**Comment by bohdan-harniuk** [comment]
Hello, @jilu1 

This task was finished without creating new singletons, so it is not a blocker. You can proceed with the code review.

Thanks, Bohdan

**Review by jilu1 — APPROVED** [review]

**Comment by jilu1** [comment]
@magento import pull request to https://github.com/magento-commerce/magento2-functional-testing-framework

**Comment by magento-engcom-team** [comment]
@jilu1 the pull request successfully imported.

**Pull request merged**
