### PR TITLE
#339 Add information about web server configuration

### PR DESCRIPTION
**Pull request by DanieliMi**
### Description
As mentioned in #339 the MFTF doesn't support executing CLI command if the web server points to `<MAGE_ROOT_DIR>/pub` as recommended in the [DevDocs](https://devdocs.magento.com/guides/v2.3/install-gde/tutorials/change-docroot-to-pub.html). I added information about it in the docs. It is not mentioned currently and might save other developers some time figuring it out (it would've saved me some time).

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/verification tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)
 - [ ] Changes to Framework doesn't have backward incompatible changes for tests or have related Pull Request with fixes to tests

### CODE REVIEW

**Comment by DanieliMi** [comment]
I'll resolve the conflicts soon.

**Comment by dobooth** [comment]
Thanks for the contribution, @DanieliMi. We need documentation PRs to point to master, so they can get picked up by our automation systems. Can you please update and rebase this PR to `master`? Thanks!

**Comment by DanieliMi** [comment]
@dobooth Shall I force push the rebase or create a new branch from master, cherry pick the commits and open a new PR? The problem is my patch branch is from develop.

**Comment by dobooth** [comment]
@DanieliMi It probably better to make a new branch from master and cherry pick.

**Comment by DanieliMi** [comment]
@jilu1 @dobooth I created a new PR #496

**Pull request closed without merging**
