### PR TITLE
Allow the webdriver to directly call upon the 'bin/magento' executable

### PR DESCRIPTION
**Pull request by powli**
### Description
Allows the MagentoWebDriver to directly call the `bin/magento` executable instead of performing CURL requests to the custom command.php endpoint. Falls back to the custom endpoint upon exception

### Fixed Issues (if relevant)
1. magento/magento2-functional-testing-framework#339: magentoCLI actions not working if docroot points to /pub

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/verification tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)
 - [ ] Changes to Framework doesn't have backward incompatible changes for tests or have related Pull Request with fixes to tests

### CODE REVIEW

**Comment by KevinBKozan** [comment]
@powli thank you for yoru contribution! I'll create an internal ticket to track progress on processing your PR, we will keep you updated as we make further progress on it.

**Comment by powli** [comment]
@okolesnyk Signed the Adobe CLA and updated the branch (I think).

**Comment by soumyau** [comment]
Hi @powli We noticed pipeline timeouts in our jenkins builds with this change, specifically with `cron:run` commands hanging endlessly waiting for `queue:consumers:start` processes to finish. Devops is investigating this issue, will keep you posted. After an internal discussion about the best way to proceed, we are reverting the changes introduced by this PR for the upcoming release `2.5.4`. Will keep you posted. Meanwhile if you have encountered similar issues, do let us know.

**Comment by tomreece** [comment]
Hi @powli 

This change has been problematic for us and our internal CICD pipeline.
This is causing us to discuss the original use-case for your change and whether it actually helps a lot of people or not.

You mention issue #339 but I think the correct solution to #339 is to tweak the NGINX configuration the same way we have to tweak the htaaccess file for Apache.
This is the preffered solution to #339 and we should document this better in DEVDOCS.

Am I missing something about your original intention?

**Comment by powli** [comment]
Hey @tomreece,

In #339 I already mentioned activating this feature via configuration (either on CLI or functional.suite.yml, see https://github.com/magento/magento2-functional-testing-framework/issues/339#issuecomment-486685736).

That would probably resolve your CICD issues, depending on where they occur. Tell me if you're interested, then I can see where I find the time. Otherwise do as you wish ;)

The original intention was avoiding the HTTP overhead by just running the commands natively, I think. It's been some time.

**Pull request merged**
