### PR TITLE
33300: Eliminated AspectMock usage from SuiteObjectHandlerTest.php

### PR DESCRIPTION
**Pull request by anzin**
### Description

I've eliminated AspectMock usage from `dev/tests/unit/Magento/FunctionalTestFramework/Suite/Handlers/SuiteObjectHandlerTest.php`

### Fixed Issues (if relevant)

1. Fixes magento/magento2#33300: [MFTF] Eliminate AspectMock from SuiteObjectHandlerTest (Complex!)

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/verification tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)
 - [ ] Changes to Framework doesn't have backward incompatible changes for tests or have related Pull Request with fixes to tests

### CODE REVIEW

**Review by andrewbess — APPROVED** [review]
Hello @anzin 
Thank you for your contribution.
Changes look well for me.

**Review by bohdan-harniuk — APPROVED** [review]
Hello, @jilu1

This task was finished without creating new singletons, so it is not a blocker. You can proceed with the code review.

Thanks, Bohdan

**Review by jilu1 — APPROVED** [review]

**Comment by jilu1** [comment]
@magento import pull request to https://github.com/magento-commerce/magento2-functional-testing-framework

**Comment by magento-engcom-team** [comment]
@jilu1 the pull request successfully imported.

**Pull request merged**
