### PR TITLE
Removing the `csharpru/vault-php-guzzle6-transport` not needed dependency

### PR DESCRIPTION
**Pull request by eduard13**
### Description
This PR aims to remove the dependency on Guzzle6transport, in order to be able to update the `guzzlehttp/guzzle` package to the latest `7.3.0` version. The current `csharpru/vault-php-guzzle6-transport` package's version, allows only `"guzzlehttp/guzzle": "~6.2"`.

### Fixed Issues (if relevant)
N/A

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/verification tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)
 - [ ] Changes to Framework doesn't have backward incompatible changes for tests or have related Pull Request with fixes to tests

### CODE REVIEW

**Comment by jilu1** [comment]
@magento import pull request to https://github.com/magento-commerce/magento2-functional-testing-framework

**Comment by magento-engcom-team** [comment]
@jilu1 the pull request successfully imported.

**Review by andrewbess — APPROVED** [review]

**Comment by jilu1** [comment]
@eduard13 
Currently Magento `platform-health` branch has  `guzzlehttp/guzzle": "^6.3.3"`, which is conflict with change in this PR. Will you bump `guzzlehttp/guzzle` version for Magento soon? If not, we will have no working branch for build.

**Comment by eduard13** [comment]
Hi @jilu1, we already have the PRs for [CE](https://github.com/magento/magento2/pull/33860) and [EE](https://github.com/magento/partners-magento2ee/pull/595), however we're still checking what's wrong with the failed builds. It might be related somehow with the MFTF forked repo that we're using temporary there.

Let's postpone this PR for now.

Thank you.

**Comment by jilu1** [comment]
> Hi @jilu1, the PRs where we're updating `guzzlehttp/guzzle` are green for both [CE](https://github.com/magento/magento2/pull/33860) and [EE](https://github.com/magento/partners-magento2ee/pull/595) (that include the changes of this PR), however let's wait delivering this until you're preparing for a new release version.
> 
> Thank you.

@eduard13
We can merge this PR to develop without making a release if you will merge [CE](https://github.com/magento/magento2/pull/33860) and [EE](https://github.com/magento/partners-magento2ee/pull/595) soon. Could you confirm?

**Comment by eduard13** [comment]
@jilu1, this will require Magento to rely on your develop branch, which isn’t the option that we’d like to go (as far as I understood). That’s why is more preferable to wait for your next release.

**Comment by jilu1** [comment]
> @jilu1, this will require Magento to rely on your develop branch, which isn’t the option that we’d like to go (as far as I understood). That’s why is more preferable to wait for your next release.

Ok, let's do that

**Comment by andrewbess** [comment]
Hello @jilu1.
We are already checking system with PHP 8.0, but we cannot run builds without these changes.
Could you please merge it into develop branch.
Thank you in advance.

**Comment by jilu1** [comment]
@andrewbess @eduard13 
Sure. Please update branch and resolve conflict.

**Review by andrewbess — APPROVED** [review]

**Comment by andrewbess** [comment]
Hello @jilu1 
The branch has been update.
There were not merge-conflicts.

**Comment by jilu1** [comment]
@magento import pull request to https://github.com/magento-commerce/magento2-functional-testing-framework

**Comment by magento-engcom-team** [comment]
@jilu1 the pull request successfully imported.

**Pull request merged**
