### PR TITLE
33581: Eliminated AspectMock where it was imported but never used

### PR DESCRIPTION
**Pull request by anzin**
### Description

I've eliminated AspectMock where it was imported but never used.

### Fixed Issues (if relevant)
1. Fixes magento/magento2#33581

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/verification tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)
 - [ ] Changes to Framework doesn't have backward incompatible changes for tests or have related Pull Request with fixes to tests

### CODE REVIEW

**Review by bohdan-harniuk — APPROVED** [review]
Hello, @anzin!
Thank you for your contribution!

Hello, @jilu1!
Please, proceed with the code review!
Here we have just code refactoring. Directly AspectMock wasn't used.

Thanks, Bohdan

**Review by andrewbess — APPROVED** [review]
Hello @anzin 
Thank you for your contribution.
Changes look good for me.

**Comment by KevinBKozan** [comment]
@magento import pull request to https://github.com/magento-commerce/magento2-functional-testing-framework

**Comment by magento-engcom-team** [comment]
@KevinBKozan the pull request successfully imported.

**Pull request merged**
