### PR TITLE
33299: Eliminated AspectMock usage from SuiteGeneratorTest.php

### PR DESCRIPTION
**Pull request by anzin**
### Description

I've eliminated AspectMock usage from `dev/tests/unit/Magento/FunctionalTestFramework/Suite/SuiteGeneratorTest.php`

### Fixed Issues (if relevant)

1. Fixes magento/magento2#33299:[MFTF] Eliminate AspectMock from SuiteGeneratorTest (Complex!)

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/verification tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)
 - [ ] Changes to Framework doesn't have backward incompatible changes for tests or have related Pull Request with fixes to tests

### CODE REVIEW

**Review by bohdan-harniuk — DISMISSED** [review]
Hello, @anzin!
Thank you for your contribution!

Hello, @jilu1!
Here was created new service (as a singleton) to mock few private methods of the SuiteGenerator class. I like this implementation. What do you think? Is it a blocker for us or we can proceed with this implementation?

**Review by bohdan-harniuk — APPROVED** [review]

**Comment by jilu1** [comment]
Removed `in progress` label. We use it when someone is actively reviewing a ticket.

**Review by andrewbess — APPROVED** [review]
Hello, @anzin!
Thank you for your contribution!

**Review by bohdan-harniuk — APPROVED** [review]
Hello, @anzin!
Thank you for your work here!

**Comment by KevinBKozan** [comment]
@magento import pull request to https://github.com/magento-commerce/magento2-functional-testing-framework

**Comment by magento-engcom-team** [comment]
@KevinBKozan the pull request successfully imported.

**Pull request merged**
