### PR TITLE
MFTF-33780: Changed loose comparisons into strict

### PR DESCRIPTION
**Pull request by bohdan-harniuk**
### Description
In this PR loose comparison operators were changed to the strict comparison operators.
These changes apply to the next comparison operators:

1. == changed to ===
2. != changed to !==

**Reason of those changes:**
With the PHP RFC updates often changes rules of loose comparison operators interpretation. So, for each MFTF codebase update to the new PHP version, if there is any update in the loose comparison operators interpretation, we must check every line of code where such operators are used to clarify if those changes applies to our codebase. A lot easier to replace loose operators with the strict ones to eliminate such problems in the future.

**This PR doesn’t cover operations that perform non-strict comparisons with the next parts:**

- functions: in_array(), array_search() and array_keys() (without declaring strict types)
- sorting functions: sort(), rsort(), asort(), arsort() and array_multisort() (with $sort_flags set to SORT_REGULAR, which is the default) 

Those cases would be considered only if any build fails on them.

**I've run all Magento 2 MFTF tests for the CE, EE, B2B repositories on the current branch:**
Screenshot 2021-08-20 at 01 58 27
Screenshot 2021-08-20 at 01 57 36

**All tests passed successfully:**
Screenshot 2021-08-20 at 12 58 42

https://github.com/magento/magento2/pull/33866

### Fixed Issues (if relevant)
1. https://github.com/magento/magento2/issues/33780: [MFTF] Investigate and fix code affected by saner string to number comparisons #33780

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/verification tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)
 - [ ] Changes to Framework doesn't have backward incompatible changes for tests or have related Pull Request with fixes to tests

### CODE REVIEW

**Comment by bohdan-harniuk** [comment]
Hello, @jilu1!

Please, proceed with the code review.

Thanks,
Bohdan.

**Comment by jilu1** [comment]
@bohdan-harniuk 
The builds are run on PHP 7, right? Let's also run on PHP 8 when the docker image is available.

**Comment by jilu1** [comment]
@magento import pull request to https://github.com/magento-commerce/magento2-functional-testing-framework

**Comment by bohdan-harniuk** [comment]
> @bohdan-harniuk
> The builds are run on PHP 7, right? Let's also run on PHP 8 when the docker image is available.

@jilu1
Yes, let’s do so!

Thanks,
Bohdan

**Comment by magento-engcom-team** [comment]
@jilu1 the pull request successfully imported.

**Comment by jilu1** [comment]
@bohdan-harniuk 
I tried to merge this PR before PHP 8 is available, but when I run on PHP 7.4, I found these 4 tests consistently fail for EE and B2B builds. The failure is not present when running with MFTF develop branch. Can you please double check?
Screen Shot 2021-08-25 at 9 28 11 AM

**Comment by bohdan-harniuk** [comment]
> @bohdan-harniuk
> I tried to merge this PR before PHP 8 is available, but when I run on PHP 7.4, I found these 4 tests consistently fail for EE and B2B builds. The failure is not present when running with MFTF develop branch. Can you please double check?
> Screen Shot 2021-08-25 at 9 28 11 AM

Hello, @jilu1!
You just need to rerun MFTF tests. There are few common issues with them. We see them quite often.
Thanks, Bohdan

**Comment by andrewbess** [comment]
Hello @jilu1 
FYI, currently, free API of currency converter is down
currency-converter-free-api-is-down
It will provoke an error in each functional test build

**Comment by jilu1** [comment]
@andrewbess @bohdan-harniuk 
I have re-run builds later to decide if we can merge this PR now or wait for validation with PHP 8.

**Review by andrewbess — APPROVED** [review]

**Comment by bohdan-harniuk** [comment]
Hello, @jilu1! 

For now free API of currency converter is up:
Screenshot 2021-09-03 at 10 09 16

Could you please rerun builds from your side? You can additionally recheck if it is UP by this link: [server-status](https://www.currencyconverterapi.com/server-status)

Thanks, Bohdan

**Review by jilu1 — APPROVED** [review]
@bohdan-harniuk 
I checked the failing tests seem to be flaky. We will merge this PR.

**Pull request merged**
