### PR TITLE
Improvement/mftf 33583 eliminate aspect mock from mock module resolver builder

### PR DESCRIPTION
**Pull request by bohdan-harniuk**
### Description
Eliminated AspectMock usage for the MockModuleResolverBuilder.

### Fixed Issues (if relevant)
1. magento/magento2#33583: [MFTF] Eliminate AspectMock from MockModuleResolverBuilder (Complex!)

Into this branch was merged the next PRs (this PR relates to them and has code changes in the files changed in that PRs):

- https://github.com/magento/magento2-functional-testing-framework/pull/850
- https://github.com/magento/magento2-functional-testing-framework/pull/844

###  Related Pull Requests
https://github.com/magento/magento2-functional-testing-framework/pull/852
https://github.com/magento/magento2-functional-testing-framework/pull/857
https://github.com/magento/magento2-functional-testing-framework/pull/843
https://github.com/magento/magento2-functional-testing-framework/pull/837
https://github.com/magento/magento2-functional-testing-framework/pull/848
https://github.com/magento/magento2-functional-testing-framework/pull/846
https://github.com/magento/magento2-functional-testing-framework/pull/845
https://github.com/magento/magento2-functional-testing-framework/pull/859
https://github.com/magento/magento2-functional-testing-framework/pull/856
https://github.com/magento/magento2-functional-testing-framework/pull/855
https://github.com/magento/magento2-functional-testing-framework/pull/842
https://github.com/magento/magento2-functional-testing-framework/pull/839
https://github.com/magento/magento2-functional-testing-framework/pull/853
https://github.com/magento/magento2-functional-testing-framework/pull/840
https://github.com/magento/magento2-functional-testing-framework/pull/844
https://github.com/magento/magento2-functional-testing-framework/pull/850

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/verification tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)
 - [ ] Changes to Framework doesn't have backwards-incompatible changes for tests or have related Pull Request with fixes to tests

### CODE REVIEW

**Comment by bohdan-harniuk** [comment]
Hello, @jilu1!

This PR should be merged after all related PRs. For now, few unit tests are failed because this PR requires all those PRs to be in the develop branch. After develop branch includes them, I will merge develop branch into this branch.

Thanks, Bohdan

**Review by andrewbess — DISMISSED** [review]
Hello @bohdan-harniuk 
Thank you for your contribution.
Great job.

**Review by jilu1 — COMMENTED** [review]
Please bring the branch up to date and resolve conflicts.

**Comment by magento-engcom-team** [comment]
@jilu1 the pull request successfully imported.

**Review by andrewbess — APPROVED** [review]

**Pull request merged**
