### PR TITLE
Issue 33296: Eliminate AspectMock from OperationDataArrayResolverTest

### PR DESCRIPTION
**Pull request by karyna-tsymbal-atwix**
### Description
Eliminated AspectMock usage from `dev/tests/unit/Magento/FunctionalTestFramework/DataGenerator/Persist/OperationDataArrayResolverTest.php`

### Fixed Issues (if relevant)

1. Fixes magento/magento2#33296: [MFTF] Eliminate AspectMock from OperationDataArrayResolverTest (Complex!)

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/verification tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)
 - [ ] Changes to Framework doesn't have backward incompatible changes for tests or have related Pull Request with fixes to tests

### CODE REVIEW

**Review by bohdan-harniuk — APPROVED** [review]
Hello, @karyna-tsymbal-atwix!
Thank you for your work here!

Hello, @jilu1!

This task was finished without creating new singletons, so it is not a blocker. You can proceed with the code review.

Thanks, Bohdan

**Review by andrewbess — APPROVED** [review]
Hello @karyna-tsymbal-atwix 
Thank you for your contribution.
It looks well for me.

**Review by eduard13 — APPROVED** [review]

**Review by jilu1 — APPROVED** [review]

**Comment by jilu1** [comment]
@magento import pull request to https://github.com/magento-commerce/magento2-functional-testing-framework

**Comment by magento-engcom-team** [comment]
@jilu1 the pull request successfully imported.

**Pull request merged**
