### PR TITLE
MFTF-33301: Eliminated AspectMock usage for TestObjectHandlerTest

### PR DESCRIPTION
**Pull request by bohdan-harniuk**
### Description
Eliminated AspectMock usage for the \tests\unit\Magento\FunctionalTestFramework\Test\Handlers\TestObjectHandlerTest.

### Fixed Issues (if relevant)
1. magento/magento2#33301: Eliminate AspectMock from TestObjectHandlerTest (Complex!)

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/verification tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)
 - [ ] Changes to Framework doesn't have backwards-incompatible changes for tests or have related Pull Request with fixes to tests

### CODE REVIEW

**Review by andrewbess — APPROVED** [review]
Hello @bohdan-harniuk 
Great changes ✅ 
Thank you for your contribution.

**Comment by bohdan-harniuk** [comment]
Hello, @jilu1

This task was finished without creating new singletons, so it is not a blocker. You can proceed with the code review.

Thanks, Bohdan

**Review by jilu1 — APPROVED** [review]

**Comment by jilu1** [comment]
@magento import pull request to https://github.com/magento-commerce/magento2-functional-testing-framework

**Comment by magento-engcom-team** [comment]
@jilu1 the pull request successfully imported.

**Comment by jilu1** [comment]
@magento import pull request to https://github.com/magento-commerce/magento2-functional-testing-framework

**Comment by magento-engcom-team** [comment]
@jilu1, an error occurred during the Pull Request import.

**Pull request merged**
