### PR TITLE
Bugfix: PHP Fatal error: MftfApplicationConfig not found in GenerateSuiteCommand

### LINKED ISSUE #471: PHP Fatal error:  MftfApplicationConfig not found in GenerateSuiteCommand
MFTF fails with fatal error due missing "use" statement

PHP Fatal error:  Uncaught Error: Class 'Magento\FunctionalTestingFramework\Console\MftfApplicationConfig' not found in /var/www/html/vendor/magento/magento2-functional-testing-framework/src/Magento/FunctionalTestingFramework/Console/GenerateSuiteCommand.php:52

### Preconditions
1.  
2. 

### Steps to reproduce
1. Use latest tag (2.5.0)
2. 
3. 

### Expected result
1.  MFTF tests to run

### Actual result
1. 
PHP Fatal error:  Uncaught Error: Class 'Magento\FunctionalTestingFramework\Console\MftfApplicationConfig' not found in /var/www/html/vendor/magento/magento2-functional-testing-framework/src/Magento/FunctionalTestingFramework/Console/GenerateSuiteCommand.php:52
Stack trace:
#0 /var/www/html/vendor/symfony/console/Command/Command.php(255): Magento\FunctionalTestingFramework\Console\GenerateSuiteCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /var/www/html/vendor/symfony/console/Application.php(893): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /var/www/html/vendor/symfony/console/Application.php(262): Symfony\Component\Console\Application->doRunCommand(Object(Magento\FunctionalTestingFramework\Console\GenerateSuiteCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www in /var/www/html/vendor/magento/magento2-functional-testing-framework/src/Magento/FunctionalTestingFramework/Console/GenerateSuiteCommand.php on line 52

### PR DESCRIPTION
**Pull request by magicsunday**
### Fixed Issues (if relevant)

1. magento/magento2-functional-testing-framework#471: PHP Fatal error: MftfApplicationConfig not found in GenerateSuiteCommand
2. ...

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/verification tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)
 - [ ] Changes to Framework doesn't have backward incompatible changes for tests or have related Pull Request with fixes to tests

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2-functional-testing-framework?pullRequest=472) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2-functional-testing-framework?pullRequest=472) before we can accept your contribution.<br/>

**Comment by KevinBKozan** [comment]
@magicsunday Thank you for your submission! We'll keep you updated with PR progress as it we review your code.

**Comment by tomreece** [comment]
This was fixed in #478 and has been released in the MFTF 2.5.1 tag.

**Comment by magicsunday** [comment]
Why another pull request with the same fix?

**Comment by tomreece** [comment]
I didn't realize there was both an Issue and a PR for this fix. So I read the issue, fixed it, and then discovered this PR after the fact.

**Pull request closed without merging**
