### PR TITLE
#389 Fix invalid bahaviour of MAGENTO_BACKEND_BASE_URL

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description
Finally - for `admin` area I've changed the method from `amOnPage` to `amOnUrl`. This solution works like a charm. Also introduced the single class to provide proper URL, as it was done inconsistently across the application

### Fixed Issues (if relevant)
1. magento/magento2-functional-testing-framework#389

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/verification tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)
 - [ ] Changes to Framework doesn't have backward incompatible changes for tests or have related Pull Request with fixes to tests

### CODE REVIEW

**Comment by KevinBKozan** [comment]
@lbajsarowicz Thank you for your contribution! I've created an internal issue to track progress on revieweing this, I'll keep you updated with comments here.

**Comment by jilu1** [comment]
@lbajsarowicz Can you share the issue you had that motivated you to make the fix? Because recently we had investigated around MAGENTO_BASE_URL and MAGENTO_BACKEND_NAME, and MFTF should be able to construct Magento backend url correctly.

**Comment by jilu1** [comment]
@lbajsarowicz I just noticed that you are trying to fix issue #389
1) MAGENTO_BACKEND_BASE_HOST was wrongly used in .env.example. It has been renamed to MAGENTO_BACKEND_BASE_URL and that's why there is no usage of MAGENTO_BACKEND_BASE_HOST mentioned in issue #389 
2) The problem becomes to re-examine all the usage of MAGENTO_BASE_URL and see if MAGENTO_BACKEND_BASE_URL needs to be considered. By looking at it, ModuleResolver.php should be covered. Have you checked it?
3) I think the persistent object handler should already handle it correctly

**Comment by lbajsarowicz** [comment]
> 1. MAGENTO_BACKEND_BASE_HOST was wrongly used in .env.example. It has been renamed to MAGENTO_BACKEND_BASE_URL and that's why there is no usage of MAGENTO_BACKEND_BASE_HOST mentioned in issue #389
Even with the right configuration - most of the tests arund Magento Admin Panel were failing. I found out that the MAGENTO_BACKEND_BASE_URL was incorrectly implemented - especially with `<amOnPage` placeholders. As you may noticed in my change - I extended the overall approach.

> 2. The problem becomes to re-examine all the usage of MAGENTO_BASE_URL and see if MAGENTO_BACKEND_BASE_URL needs to be considered. By looking at it, ModuleResolver.php should be covered. Have you checked it?
Looks like I forgot to cover it.

> 3. I think the persistent object handler should already handle it correctly
What actually?

**Comment by lbajsarowicz** [comment]
Module Resolver refactored, too... 
I also extracted a few elements to separate methods.

**Comment by lbajsarowicz** [comment]
After changes to Module Resolver, the API Key request does not work properly. I'm investigating that.

**Comment by lbajsarowicz** [comment]
@jilu1 Calling you for review.

**Comment by lbajsarowicz** [comment]
@okolesnyk / @jilu1 Any updates?

**Comment by lbajsarowicz** [comment]
There's nothing about to happen regarding that. 
Closing PR.

**Comment by soumyau** [comment]
@lbajsarowicz can you resolve conflicts on this branch, so that I can test this out on builds/ configurations?

**Comment by lbajsarowicz** [comment]
I'll do that in the night

**Comment by soumyau** [comment]
@lbajsarowicz since this is configuration related bug-fix, we intend to roll this out for both 2.x and 3.x releases. Can I also request you to create pull requests to both, `develop` as well as a patch to 2.x (last patch release being `2.6.4`)? 
Thank you!

**Comment by lbajsarowicz** [comment]
Please test it very thoroughly, as I was working on this at the very beginning of the year. Now we have almost July, so some things have changed :-)

**Comment by lbajsarowicz** [comment]
I'll provide that for `develop` during the weekend
Thank you for the review.

**Comment by soumyau** [comment]
> I'll provide that for `develop` during the weekend

@lbajsarowicz any updates on your PR to `develop`? Thanks!

**Pull request merged**
